version: v13
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /.+
  script: main.app

libraries:
- name: lxml
  version: "2.3.5"
